dist: trusty
language: java
sudo: true
jdk:
  - openjdk12
  - oraclejdk11
  - openjdk10
  - oraclejdk9
  - oraclejdk8
  - openjdk7
script: mvn clean verify
after_success:
  - mvn clean test org.jacoco:jacoco-maven-plugin:report org.eluder.coveralls:coveralls-maven-plugin:report