dist: trusty
language: java
sudo: true
jdk:
  - openjdk12
  - oraclejdk11
  - openjdk10
  - oraclejdk9
  - oraclejdk8
  - openjdk7
matrix:
  allow_failures:
    - jdk: openjdk7
script: mvn clean verify
